version: '3.9'
networks:
  my_network:
    driver: bridge
services:
  db:
    container_name: posgress_db
    image: postgres
    restart: always
    networks:
      - my_network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Seta2022!
      POSTGRES_DB: postgres
  app:
    build: .
    ports:
      - 3001:3001
    networks:
      - my_network